config/routes.rb
# -*- encoding : utf-8 -*-
Retorica::Application.routes.draw do

  root :to => redirect('dashboards/first')

  get '/about' => 'welcome#about', :as => 'about'

  resources :dashboards, :except => [:new, :create, :edit, :update, :destroy] do
    collection { get :first }
  end

  resources :deputados, :except => [:new, :create, :update, :destroy]

end

app/models/dashboard.rb
class Dashboard
  include Mongoid::Document

  field :title, type: String
  field :slug, type: String
  field :description, type: String

  has_many :topics

  def serializable_hash(options)
    super({:include => [:topics]}.merge(options))
  end
end

app/models/deputado.rb
# -*- encoding : utf-8 -*-
class Deputado
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  has_mongoid_attached_file :foto

  field :ide_cadastro, type: String
  field :situacao, type: String
  field :site_deputado, type: String
  field :foto_url, type: String
  field :nome_parlamentar, type: String
  field :num_legislatura, type: Integer
  field :sexo, type: String
  field :email, type: String

  has_and_belongs_to_many :partidos
  has_and_belongs_to_many :unidade_federativa

  has_many :emphases, :class_name => 'Emphasis'

  validates_attachment :foto, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def serializable_hash(options)
    super({
      include: [:partidos, :unidade_federativa, :foto_url]
    }.merge(options || {}))
  end

  def foto_url
    if foto.exists?
      foto.url
    else
      ActionController::Base.helpers.asset_path 'null.jpeg'
    end
  end
end

app/models/discurso.rb
class Discurso
  include Mongoid::Document

  embeds_one :fase_sessao

  field :autor, type: String
  field :conteudo, type: String
  field :conteudo_plain_text, type: String
  field :conteudo_stemmed, type: String
  field :numero_insercao, type: Integer
  field :numero_orador, type: Integer
  field :proferido_em, type: DateTime
  field :sessao, type: String

end

app/models/emphasis.rb
class Emphasis
  include Mongoid::Document

  field :name, type: String
  field :emphasis, type: Float

  belongs_to :topic
  belongs_to :deputado

  def serializable_hash(options)
    super({:include => [:deputado]}.merge(options))
  end
end

app/models/fase_sessao.rb
class FaseSessao
  include Mongoid::Document

  field :codigo, type: String
  field :descricao, type: String
  embedded_in :discurso
end

app/models/partido.rb
# -*- encoding : utf-8 -*-
class Partido
  include Mongoid::Document
  include Mongoid::Timestamps

  field :nome, type: String
  field :sigla, type: String

  has_and_belongs_to_many :deputados


  def serializable_hash(options)
    super({ only: [:sigla]}.merge(options || {}))
  end

end

app/models/topic.rb
class Topic
  include Mongoid::Document

  field :title, type: String
  field :ignore, type: Mongoid::Boolean
  field :observ, type: Mongoid::Boolean

  belongs_to :dashboard

  has_many :emphases, :class_name => 'Emphasis'

  def serializable_hash(options)
    super({:include => [:emphases]}.merge(options))
  end

end

app/models/unidade_federativa.rb
class UnidadeFederativa
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sigla, type: String

  has_and_belongs_to_many :deputados
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, :only => [:show]

  respond_to :html, :json

  def index
    respond_with Dashboard.all
  end

  def show
    respond_with @dashboard
  end

  def first
    first_url = url_for Dashboard.last
    return redirect_to first_url
  end

  protected

    def set_dashboard
      @dashboard = Dashboard.where(:_id => params[:id]).first
    end

end

app/controllers/deputados_controller.rb
# -*- encoding : utf-8 -*-
class DeputadosController < ApplicationController
  before_action :set_deputado, only: [:show]

  # GET /deputados
  # GET /deputados.json
  def index
    Deputado.all
    respond_to do |format|
      format.json {}
    end
  end

  # GET /deputados/1
  # GET /deputados/1.json
  def show
    respond_to do |format|
      format.json{}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deputado
    @deputado = Deputado.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def deputado_params
    params.require(:deputado).permit(:nome_parlamamentar, :partido, :sexo, :unidade_federativa, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  layout 'dashboards' 
  
  def about
  end
  
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def bubbles_data_url
  end
end

app/helpers/deputados_helper.rb
# -*- encoding : utf-8 -*-
module DeputadosHelper
end

app/views/dashboards/index.html.erb
<h1>Dashboards</h1>

<ul>
  <% Dashboard.all.each do |dashboard| %>
    <li><a href="<%= url_for dashboard %>"><%= dashboard.title %></a></li>
  <% end %>
</ul>

app/views/dashboards/show.html.erb
<div class="loading">
  <div class="signal">
  </div>
</div>    
<div class="popover"><span class="nome">ABELARDO CAMARINHA</span>
  <div class="partido">PSB / SP</div>
  <div class="tick"></div>
</div>
<div class="popover2"><span class="nome">ABELARDO CAMARINHA</span>
  <div class="tick"></div>
</div>
<div class="row no-gutter">
  <div class="col-md-3 full-height">
    <div class="content-description">
      <div class="logo"><%= image_tag("logo.png") %></div>
      <h1 class="title">Retórica Parlamentar<sup>beta</sup></h1>  
      <div class="description">
        <div class="input-group margin-bottom-sm busca">
          <span class="input-group-addon"><i class="fa fa-search fa-fw"></i></span>
          <input class="typeahead" type="text" placeholder="Buscar deputados">
        </div>
        <div class="info">
          <h3 class="name"></h3>
          <p class="part"></p>
          <p class="email"></p>
          <a href="http://www.mozilla.com/" target="_blank" class="site"></a>
        </div>

        <div class="row temas">
          <h3>Temas</h3>

          <table>
            <tbody>
            </tbody>
          </table>
        </div>

        <div class="intro">
          <p class="headline">Visualização da ênfase por <a id="temas" class="in-link" href="#">temas</a> dos deputados brasileiros durante seus discursos.</p>
          <p class="detail">Dos mais de 84 mil discursos proferidos por deputados levantamos os 70 principais temas e quais os deputados mais relacionados com cada um deles.</p>
        </div>      
      </div>
      <div class="foot">
        <!--<%= image_tag("selo_colaborativo.png", :alt => "Selo colaborativo Labhacker", :class => "selo") %>-->
        <p><a href="<%= about_url %>"><i class="fa fa-info-circle"></i> Saiba mais</a></p>
        <div class="github">
          <iframe src="http://ghbtns.com/github-btn.html?user=labhackercd&repo=Retorica&type=fork&count=true"
    allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
          <iframe src="http://ghbtns.com/github-btn.html?user=labhackercd&repo=Retorica&type=watch&count=true"
    allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
        </div>
      </div>
    </div>    
  </div>
  <div class="col-md-9 no-float">
    <svg id="main">
    </svg>
  </div> 
</div>
<div class="dropdown ano">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    <span class="label"><%= @dashboard.title %></span>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <% Dashboard.nin(_id: [@dashboard.id]).each do |dashboard| %>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= url_for dashboard %>"><%= dashboard.title %></a></li>
    <% end %>
  </ul>
</div>


<script type="text/javascript">
  doTheThing("<%= dashboard_url(:id => @dashboard.id, :format => :json) %>");
</script>

app/views/deputados/discursos.html.erb
<%= 'Arquivo Importado com Sucesso' %>

app/views/deputados/import.html.erb
<%= 'Arquivo Importado com Sucesso' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<script type="text/javascript">
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
    }, 2000);
</script>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
 	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Retorica Parlamentar" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Retorica Parlamentar" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
 </head>
<body>
	<main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
</body>
</html>

app/views/layouts/dashboards.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Retorica Rails" %>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <title><%= content_for?(:title) ? yield(:title) : "Retorica Parlamentar" %></title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Oswald', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/welcome/about.html.erb
  <div class="content-description about">
    
    <a href="/"><i class="fa fa-reply fa-2x"></i></a>
   
    <a href="/" class="logo">
    <div class="logo">
      <%= image_tag("logo.png") %>
      <h1 class="title">Retórica Parlamentar<sup>beta</sup></h1>        
    </div>
    </a>
    
    <div class="row rp">
      

      <div class="col-md-4">
       <p> O Laboratório Hacker, em parceria com o Departamento de Taquigrafia, Revisão e Redação e o Centro de Informática, lança o Aplicativo Retórica Parlamentar, ideia concebida na 1ª Maratona Hacker (desenvolvido por Davi Moreira, Manoel Galdino e Luis Carli) promovida pela Câmara dos Deputados e desenvolvida durante o ano de 2014, a partir do acesso direto e livre de dados abertos. </p>
      </div>
      <div class="col-md-4">
        <p> O APP, espaço de divulgação de discursos parlamentar, busca promover a transparência do mandato e fornecer subsídios para o controle social com a divulgação dos temas mais debatidos em Plenário na 54ª Legislatura – 2011 a 2015.</p>
      </div>
      <div class="col-md-4">
            <p>O Retórica é um projeto experimental de software livre, de caráter interativo entre a Câmara e a sociedade.</p>
            <p>Todo o código aberto do Retórica Parlamentar está no Github:</p>
            <div class="github">
              <iframe src="http://ghbtns.com/github-btn.html?user=labhackercd&repo=Retorica&type=fork&count=true"
        allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
              <iframe src="http://ghbtns.com/github-btn.html?user=labhackercd&repo=Retorica&type=watch&count=true"
        allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
            </div>
      </div>
    </div>

           <h2>Metodologia do Retórica Parlamentar<sup>beta</sup></h2>

    <div class="cold-md-6"><p>Este projeto faz uso dos <a href="http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/sessoesreunioes-2/sessoesreunioes-1" target="_blank">dados abertos</a> da Câmara dos deputados 
    para processar os discursos de cada um dos deputados. De posse dos discursos, dividimos os discursos por cada ano da legislatura e processamos segundo o <a href="http://web.stanford.edu/~jgrimmer/ExpAgendaFinal.pdf" target="_blank">Modelo Matemático  de Processamento dos Discursos Parlamentares</a>. Após o processamento, obtemos uma planilha, que pode ser vista <a href="https://docs.google.com/spreadsheets/d/1GFD8PwT5aQ0JTe2yReUNCpz_0iHvJC1SBayrS5qeNwk/edit?usp=sharing" target="_blank">aqui</a>, onde cada linha de  palavras (reduzidas) que compõem cada um dos temas. Em outra saída, calculamos um indíce de cada parlamentar com relação a aquele tema, que foi determinado do retórica. Por fim, colocamos os deputados nas bolhas, com o tamanho proporcional calculado pelo retórica.</p></div>
    
      <h2>Tecnologias do Retórica Parlamentar<sup>beta</sup></h2>
      <div class="row tec">
        <div class="col-md-3"><%= image_tag("ruby_logo.png", :alt => "Ruby") %></div>
        <div class="col-md-3"><%= image_tag("python_logo.png", :alt => "Python") %></div>
        <div class="col-md-3"><h1>R</h1></div>
        <div class="col-md-3"><%= image_tag("d3_logo.png", :alt => "d3.js") %></div>
      </div>
    </div>
  </div>